[tool.bumpversion]
    commit = true
    current_version = "26.4.1"
    parse = """(?x)                 # Verbose mode
    (?P<release>                    # The release part
        (?:[0-9]{2})\\.             # YY.
        (?:1[0-2]|[1-9])            # M or MM
    )
    \\.(?P<patch>\\d+)              # .patch
"""
    pre_commit_hooks = ["uv lock", "git add uv.lock"]
    serialize = ["{release}.{patch}"]
    tag = true
    tag_name = "v{new_version}"

    [[tool.bumpversion.files]]
        filename = "pyproject.toml"
        replace  = 'version = "{new_version}"'
        search   = 'version = "{current_version}"'

    [tool.bumpversion.parts.release]
        calver_format = "{0Y}.{MM}"

    [tool.bumpversion.parts.patch]
        first_value = 0
