[format.rules]
    array-bracket-space-width         = 0
    array-comma-space-width           = 1
    group-blank-lines-limit           = 2
    indent-style                      = "space"
    indent-sub-tables                 = true
    indent-table-key-value-pairs      = true
    indent-width                      = 4
    inline-table-brace-space-width    = 1
    inline-table-comma-space-width    = 1
    key-value-equals-sign-alignment   = true
    key-value-equals-sign-space-width = 1
    line-width                        = 88
    trailing-comment-alignment        = true
