[[repos]]
    hooks = [
        { entry = "taplo format", id = "taplo-format", language = "system", name = "taplo-format", types_or = [
            "toml",
        ] },
    ]
    repo = "local"

[[repos]]
    hooks = [
        # Run the linter.
        { args = ["--fix"], id = "ruff-check", types_or = ["pyi", "python"] },

        # Run the formatter.
        { id = "ruff-format", types_or = ["pyi", "python"] },
    ]
    repo = "https://github.com/astral-sh/ruff-pre-commit"
    rev = "v0.15.21" # Ruff version.

[[repos]]
    hooks = [
        { entry = ".venv/bin/pytest tests", id = "pytest", language = "system", name = "pytest", pass_filenames = false, types_or = [
            "pyi",
            "python",
        ] },
    ]
    repo = "local"
