[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64"]

[project]
authors = [
    { email = "jackadamson@gmail.com", name = "Jack Adamson" },
    { email = "jhpyle@gmail.com", name = "Jonathan Pyle" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
]
dependencies = [
    "PyYAML",
    "click",
    "gitmatch",
    "packaging",
    "requests",
    "watchdog",
]
description = "Multi-platform CLI utility for working with docassemble packages and servers"
keywords = ["docassemble"]
license = { file = "LICENSE" }
name = "docassemblecli3"
readme = "README.md"
requires-python = ">= 3.10"
version = "0.5.1"

[project.urls]
"Bug Tracker" = "https://github.com/jpagh/docassemblecli3/issues"
"Homepage" = "https://github.com/jpagh/docassemblecli3"

[project.scripts]
da = "docassemblecli3:cli"
docassemblecli3 = "docassemblecli3:cli"

[tool.ruff]
line-length = 120
