[project]
    name            = "docassemblecli3"
    version         = "26.7.0"
    description     = "Multi-platform CLI utility for working with docassemble packages and servers"
    readme          = "README.md"
    requires-python = ">= 3.12"
    license         = "MIT"
    license-files   = ["LICENSE"]
    authors         = [
        { name = "Jack Adamson", email = "jackadamson@gmail.com" },
        { name = "Jonathan Pyle", email = "jhpyle@gmail.com" },
    ]
    keywords        = [
        "docassemble",
    ]
    classifiers     = [
        "Programming Language :: Python",
    ]
    dependencies    = [
        "click>=8.3.2",
        "gitmatch>=0.3.0",
        "niquests>=3.18.4",
        "packaging>=26.0",
        "pyyaml>=6.0.3",
        "watchdog>=6.0.0",
        "xxhash>=3.5.0",
    ]

    [project.urls]
        "Bug Tracker" = "https://github.com/jpagh/docassemblecli3/issues"
        "Homepage"    = "https://github.com/jpagh/docassemblecli3"

    [project.scripts]
        da              = "docassemblecli3:cli"
        docassemblecli3 = "docassemblecli3:cli"

[dependency-groups]
    dev = [
        "pytest>=9.0.2",
        "pytest-cov>=7.1.0",
        "pytest-xdist>=3.8.0",
    ]

[build-system]
    requires      = ["uv_build>=0.12.0,<0.13"]
    build-backend = "uv_build"

[tool.coverage.run]
    branch         = true
    omit           = [
        "tests/*",
    ]
    relative_files = true
    source         = [
        "docassemblecli3",
    ]

[tool.coverage.report]
    omit = [
        "tests/*",
    ]

[tool.ruff]
    line-length = 120

    [tool.ruff.lint]
        extend-select = [
            "I",
        ]
